name: hackathon_frontend
description: "Work Distribution System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_builder: ^0.7.0
  clipboard: ^0.1.3
  drag_and_drop_lists: ^0.3.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  lottie:
  flutter_html: ^2.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

assets:
  - assets/
  - assets/static
