# Generated by Django 4.2.7 on 2023-11-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_repo',
            field=models.URLField(blank=True, editable=False, max_length=100),
        ),
    ]
