# Generated by Django 4.2.7 on 2023-11-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_git_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='Category',
            field=models.IntegerField(blank=True, choices=[(0, 'UI/UX designer'), (1, 'Frontend Dev'), (2, 'Content Designer'), (3, 'DBMS Engineer'), (4, 'Backend Developer'), (5, 'Security Developer'), (6, 'Quality Analysis')], default=0),
        ),
    ]
